---
title: "The new version"
author: "Krutika Chauhan"
date: "2022-10-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
##Libraries
library(haven)
library(readr) 
library(dplyr)
library(plyr)
library(ggplot2)
```

```{r, chunk7}
library(haven)
df = read_csv("/Users/krutika/Downloads/titanic.csv")
```


```{r}
#mean
mean(df$Age, na.rm = TRUE)
```

```{r}
group.means<-ddply(df,c("Pclass"),summarise,mean=mean(Age))
group.means
```
###bgit remote remove 
```{r}
aggregate(df$Age,         # Median by group
          list(df$Pclass),
          median)
```

```{r}
out <- boxplot.stats(df$Age)$out
boxplot(df$Age ~ df$Pclass, range = 1,
  ylab = "Age", xlab = "Pclass"
)
mtext(paste("Outliers: ", paste(out, collapse = ", ")))
```


###boxplot
```{r}
# Boxplot from dataframe
boxplot(df$Age ~ df$Pclass, range = 1, outline = TRUE, 
        horizontal = TRUE, col = c('red', 'blue', 'yellow'),
        main = 'Age by Pclass', 
        ylab = 'Pclass', xlab = 'Age',
        names = c('One', 'Two', 'Three'))
```

```{r}
library(dplyr)
df %>% 
     group_by(Pclass) %>% 
  dplyr::summarise(sum(df$Sex == "male")/length(df$Sex), sum(df$Sex == "female")/length(df$Sex))
```

```{r}
table3 <- table(df$Sex, df$Pclass)
prop.table(table3)
```







